-- Config.lua — GarbageGoober operator config. Edit this file, then run  goober reload
-- in chat (or restart the server) to apply. Returns one table.
--
-- HOW MATCHING WORKS
--   For each loose item the sorter builds a category PATH from `rules` below,
--   ordered general -> specific (e.g. { Trader, Category } or, for guns,
--   { Trader, Category, Sub-type }). It then looks for a chest IN THE SAME FLAG
--   whose custom name matches a path node, trying the MOST-SPECIFIC node first
--   and falling back toward the general end. First hit wins. No match =>
--   defaultPath (or left). Paths may be any depth.
--
--   Example: a 12ga slug is { "Armorer", "Ammo" } -> tries "Ammo" then "Armorer".
--   An AK-47 is { "Armorer", "RangedWeapon", "AutomaticRifles" } -> tries
--   "AutomaticRifles", then "RangedWeapon", then "Armorer".
--
-- THE TREE = SCUM's vendor structure: TRADER TYPE > TRADE CATEGORY.
--   Trader types (ETraderType) used as the coarse/fallback level:
--     Armorer  Bartender  Doctor  Mechanic  Harbourmaster  GeneralGoods
--   Trade categories (ETradeCategory) are the leaves — these are FLAT in SCUM
--   (Drink, Food, Feet, Ammo... are all peers; there is no "Clothing" or
--   "Consumables" category):
--     Armorer       -> Ammo RangedWeapon RangedWeaponAccessories MeleeWeapon Explosives
--     Bartender     -> Food Drink Alcohol
--     Doctor        -> FirstAid
--     Mechanic      -> Vehicles Crafting
--     Harbourmaster -> WaterVehicles Fishing
--     GeneralGoods  -> Helmets Jackets Pants Tops Headwear Hands Face Feet
--                      Backpacks Armour Neckwaist Underwear Cosmetics Misc
--   Name a chest after a leaf (e.g. "Drink", "Feet", "Ammo") for fine sorting,
--   or after a trader (e.g. "Bartender", "GeneralGoods") to catch a whole group.
--
-- COMPLETING THE TREE: the `match` tokens are a starting point; not every SCUM
-- item is guessed correctly here. Run  goober classes  to dump the real class
-- names in the world and how each maps, and watch the sweep log's "unmapped"
-- line — then add/fix rules below.

return {
    -- ---- behaviour -------------------------------------------------------
    sweepIntervalMs = 60000,  -- sweep period (ms); restart to change; "goober now" = on demand
    flagRadiusOverride = nil, -- nil = live ConZBaseManager._flagInfluenceRadius (5000cm)
    nameContains = false,     -- false = exact chest-name match; true = substring

    -- Commands are typed in NORMAL chat starting with this word, e.g. "goober now".
    -- (No "#" — that goes through SCUM's admin processor and replies "Unrecognized
    -- command".) The trigger word still appears in chat to whoever shares the channel.
    chatTrigger = "goober",
    -- Only let SCUM admins drive the mod via chat (normal chat has no privilege gate).
    -- true = require IsUserAdmin; false = anyone can type the command.
    requireAdmin = true,

    -- ---- per-player / per-flag entitlement gate --------------------------
    -- When ON, the sweep only sorts loot inside a flag whose owner has been
    -- entitled by an admin (the donation/premium model), with a per-flag
    -- override as the fallback. A flag's owner is NOT readable from the live
    -- actor, so the mod reads SCUM.db read-only via the bundled sqlite3.exe to
    -- map baseId -> owner Steam64 -> entitled?. Control it in-game with:
    -- goober add/remove <player> , goober list , goober status ,
    -- goober flag on|off|clear [baseId] , goober default on|off .
    --   true  = gate sorting by entitlement (per-player primary, per-flag fallback)
    --   false = sort EVERY flag (the entitlement layer is disabled)
    entitlementsEnabled = true,
    -- Path to the server's save DB (read-only). owner_user_profile_id lives here.
    dbPath = [[C:\scumserver\SCUM\Saved\SaveFiles\SCUM.db]],
    -- sqlite3.exe used to read the DB. nil = use the copy in this mod's folder
    -- (run install-libraries.ps1 to fetch it). Set a path to use a different one.
    sqliteExe = nil,
    -- How often (ms) the sweep re-reads the DB to refresh the owner map. Cheap
    -- (one read-only query). Lower = a donor's freshly built/rebuilt base starts
    -- being sorted sooner; higher = fewer sqlite spawns. add/remove/flag/default
    -- commands always force an immediate refresh regardless of this.
    resyncIntervalMs = 300000, -- 5 min

    -- ---- category rules (path = { Trader, Category }) --------------------
    -- First rule whose `match` substring (case-insensitive) is found in the
    -- item's class name wins. Order: specific/risky tokens BEFORE general ones.
    rules = {
        -- ===== PRIORITY OVERRIDES (checked first; fix a few over-broad tokens below) =====
        { match = "car_battery", path = { "Mechanic", "Crafting" } },
        { match = "agaricus", path = { "Bartender", "Food" } },
        { match = "bakingsoda", path = { "Bartender", "Food" } },
        { match = "firecracker", path = { "Mechanic", "Crafting" } },
        { match = "double_bang", path = { "Mechanic", "Crafting" } },
        { match = "beanie", path = { "GeneralGoods", "Headwear" } },
        { match = "beenie", path = { "GeneralGoods", "Headwear" } },
        { match = "scarf", path = { "GeneralGoods", "Headwear" } },
        { match = "headband", path = { "GeneralGoods", "Headwear" } },
        { match = "activatedcharcoal", path = { "Doctor", "FirstAid" } },
        { match = "phoenix_tears", path = { "Doctor", "FirstAid" } },
        { match = "axe_head", path = { "Mechanic", "Crafting" } },
        { match = "fishingbait", path = { "Harbourmaster", "Fishing" } },
        { match = "fish_", path = { "Harbourmaster", "Fishing" } },
        { match = "1h_", path = { "Armorer", "MeleeWeapon" } },
        { match = "2h_", path = { "Armorer", "MeleeWeapon" } },

        -- ===== ARMORER =====
        -- ammo first (so e.g. "rifle_ammo" matches Ammo, not RangedWeapon)
        { match = "_slug",       path = { "Armorer", "Ammo" } },
        { match = "birdshot",    path = { "Armorer", "Ammo" } },
        { match = "buckshot",    path = { "Armorer", "Ammo" } },
        { match = "_ammo",       path = { "Armorer", "Ammo" } },
        { match = "cartridge",   path = { "Armorer", "Ammo" } },
        { match = "_rounds",     path = { "Armorer", "Ammo" } },
        { match = "magazine",    path = { "Armorer", "Ammo" } },
        { match = "_mag_",       path = { "Armorer", "Ammo" } },
        { match = "_arrow",      path = { "Armorer", "Ammo" } },
        { match = "_bolt",       path = { "Armorer", "Ammo" } },
        -- weapon accessories before weapons
        { match = "scope",       path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "silencer",    path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "suppressor",  path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "_sight",      path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "foregrip",    path = { "Armorer", "RangedWeaponAccessories" } },
        -- explosives
        { match = "grenade",     path = { "Armorer", "Explosives" } },
        { match = "explosive",   path = { "Armorer", "Explosives" } },
        { match = "_c4",         path = { "Armorer", "Explosives" } },
        { match = "claymore",    path = { "Armorer", "Explosives" } },
        { match = "molotov",     path = { "Armorer", "Explosives" } },
        -- melee
        { match = "machete",     path = { "Armorer", "MeleeWeapon" } },
        { match = "knife",       path = { "Armorer", "MeleeWeapon" } },
        { match = "_axe",        path = { "Armorer", "MeleeWeapon" } },
        { match = "hatchet",     path = { "Armorer", "MeleeWeapon" } },
        { match = "cleaver",     path = { "Armorer", "MeleeWeapon" } },
        { match = "crowbar",     path = { "Armorer", "MeleeWeapon" } },
        { match = "sledgehammer",path = { "Armorer", "MeleeWeapon" } },
        { match = "_bat",        path = { "Armorer", "MeleeWeapon" } },
        { match = "spear",       path = { "Armorer", "MeleeWeapon" } },
        { match = "shovel",      path = { "Armorer", "MeleeWeapon" } },
        { match = "pickaxe",     path = { "Armorer", "MeleeWeapon" } },
        { match = "pitchfork",   path = { "Armorer", "MeleeWeapon" } },
        { match = "scythe",      path = { "Armorer", "MeleeWeapon" } },
        { match = "sickle",      path = { "Armorer", "MeleeWeapon" } },
        { match = "kukri",       path = { "Armorer", "MeleeWeapon" } },
        { match = "baton",       path = { "Armorer", "MeleeWeapon" } },
        -- ranged weapons -> sub-typed by EWeaponCategory where the class name
        -- reveals it; specific tokens first, generic 'rifle' then 'weapon_' last.
        -- handguns
        { match = "pistol",      path = { "Armorer", "RangedWeapon", "Handguns" } },
        { match = "revolver",    path = { "Armorer", "RangedWeapon", "Handguns" } },
        { match = "glock",       path = { "Armorer", "RangedWeapon", "Handguns" } },
        { match = "makarov",     path = { "Armorer", "RangedWeapon", "Handguns" } },
        { match = "deagle",      path = { "Armorer", "RangedWeapon", "Handguns" } },
        { match = "_m1911",      path = { "Armorer", "RangedWeapon", "Handguns" } },
        { match = "_m9",         path = { "Armorer", "RangedWeapon", "Handguns" } },
        -- submachine guns
        { match = "submachine",  path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "_smg",        path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "mp5",         path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "mp7",         path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "mp40",        path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "_uzi",        path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "thompson",    path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "korpion",     path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        { match = "kriss",       path = { "Armorer", "RangedWeapon", "SubmachineGuns" } },
        -- shotguns
        { match = "shotgun",     path = { "Armorer", "RangedWeapon", "Shotguns" } },
        { match = "spas",        path = { "Armorer", "RangedWeapon", "Shotguns" } },
        { match = "mossberg",    path = { "Armorer", "RangedWeapon", "Shotguns" } },
        { match = "sawed_off",   path = { "Armorer", "RangedWeapon", "Shotguns" } },
        { match = "saiga",       path = { "Armorer", "RangedWeapon", "Shotguns" } },
        -- sniper rifles
        { match = "sniper",      path = { "Armorer", "RangedWeapon", "SniperRifles" } },
        { match = "_svd",        path = { "Armorer", "RangedWeapon", "SniperRifles" } },
        { match = "dragunov",    path = { "Armorer", "RangedWeapon", "SniperRifles" } },
        { match = "kar98",       path = { "Armorer", "RangedWeapon", "SniperRifles" } },
        { match = "_m24",        path = { "Armorer", "RangedWeapon", "SniperRifles" } },
        { match = "barrett",     path = { "Armorer", "RangedWeapon", "SniperRifles" } },
        -- automatic rifles
        { match = "ak47",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "ak74",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_akm",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_m16",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_m4a1",       path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_m4_",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_scar",       path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_aug",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_fal",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "_g36",        path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "famas",       path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "hk416",       path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "automatic_rifle", path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        { match = "assault_rifle",   path = { "Armorer", "RangedWeapon", "AutomaticRifles" } },
        -- bows
        { match = "crossbow",    path = { "Armorer", "RangedWeapon", "Bow" } },
        { match = "longbow",     path = { "Armorer", "RangedWeapon", "Bow" } },
        { match = "recurve",     path = { "Armorer", "RangedWeapon", "Bow" } },
        { match = "compound_bow",path = { "Armorer", "RangedWeapon", "Bow" } },
        { match = "bow_",        path = { "Armorer", "RangedWeapon", "Bow" } },
        -- throwing
        { match = "throwing",    path = { "Armorer", "RangedWeapon", "ThrowingWeapons" } },
        -- generic rifles (after the specific rifle types above)
        { match = "_sks",        path = { "Armorer", "RangedWeapon", "Rifles" } },
        { match = "mosin",       path = { "Armorer", "RangedWeapon", "Rifles" } },
        { match = "_m14",        path = { "Armorer", "RangedWeapon", "Rifles" } },
        { match = "lever_action",path = { "Armorer", "RangedWeapon", "Rifles" } },
        { match = "rifle",       path = { "Armorer", "RangedWeapon", "Rifles" } },
        -- any other gun -> generic RangedWeapon
        { match = "weapon_",     path = { "Armorer", "RangedWeapon" } },

        -- ===== DOCTOR =====
        { match = "bandage",     path = { "Doctor", "FirstAid" } },
        { match = "antibiotic",  path = { "Doctor", "FirstAid" } },
        { match = "painkiller",  path = { "Doctor", "FirstAid" } },
        { match = "antiseptic",  path = { "Doctor", "FirstAid" } },
        { match = "suture",      path = { "Doctor", "FirstAid" } },
        { match = "vitamin",     path = { "Doctor", "FirstAid" } },
        { match = "morphine",    path = { "Doctor", "FirstAid" } },
        { match = "_pills",      path = { "Doctor", "FirstAid" } },
        { match = "syringe",     path = { "Doctor", "FirstAid" } },
        { match = "medkit",      path = { "Doctor", "FirstAid" } },
        { match = "first_aid",   path = { "Doctor", "FirstAid" } },
        { match = "gauze",       path = { "Doctor", "FirstAid" } },
        { match = "splint",      path = { "Doctor", "FirstAid" } },
        { match = "disinfect",   path = { "Doctor", "FirstAid" } },
        { match = "epinephrine", path = { "Doctor", "FirstAid" } },
        { match = "tourniquet",  path = { "Doctor", "FirstAid" } },
        { match = "ointment",    path = { "Doctor", "FirstAid" } },
        { match = "tetracycline",path = { "Doctor", "FirstAid" } },

        -- ===== BARTENDER =====
        -- alcohol (before drink)
        { match = "beer",        path = { "Bartender", "Alcohol" } },
        { match = "whiskey",     path = { "Bartender", "Alcohol" } },
        { match = "wine",        path = { "Bartender", "Alcohol" } },
        { match = "vodka",       path = { "Bartender", "Alcohol" } },
        { match = "_rum",        path = { "Bartender", "Alcohol" } },
        { match = "moonshine",   path = { "Bartender", "Alcohol" } },
        -- drink
        { match = "water",       path = { "Bartender", "Drink" } },
        { match = "cola",        path = { "Bartender", "Drink" } },
        { match = "juice",       path = { "Bartender", "Drink" } },
        { match = "milk",        path = { "Bartender", "Drink" } },
        { match = "soda",        path = { "Bartender", "Drink" } },
        { match = "coffee",      path = { "Bartender", "Drink" } },
        { match = "_tea",        path = { "Bartender", "Drink" } },
        { match = "lemonade",    path = { "Bartender", "Drink" } },
        -- food
        { match = "canned",      path = { "Bartender", "Food" } },
        { match = "meat",        path = { "Bartender", "Food" } },
        { match = "_egg",        path = { "Bartender", "Food" } },
        { match = "bread",       path = { "Bartender", "Food" } },
        { match = "cheese",      path = { "Bartender", "Food" } },
        { match = "apple",       path = { "Bartender", "Food" } },
        { match = "_pear",       path = { "Bartender", "Food" } },
        { match = "banana",      path = { "Bartender", "Food" } },
        { match = "corn",        path = { "Bartender", "Food" } },
        { match = "bean",        path = { "Bartender", "Food" } },
        { match = "chocolate",   path = { "Bartender", "Food" } },
        { match = "cereal",      path = { "Bartender", "Food" } },
        { match = "_rice",       path = { "Bartender", "Food" } },
        { match = "carrot",      path = { "Bartender", "Food" } },
        { match = "potato",      path = { "Bartender", "Food" } },
        { match = "tomato",      path = { "Bartender", "Food" } },
        { match = "cabbage",     path = { "Bartender", "Food" } },
        { match = "mushroom",    path = { "Bartender", "Food" } },
        { match = "onion",       path = { "Bartender", "Food" } },
        { match = "garlic",      path = { "Bartender", "Food" } },
        { match = "lettuce",     path = { "Bartender", "Food" } },
        { match = "pumpkin",     path = { "Bartender", "Food" } },
        { match = "cucumber",    path = { "Bartender", "Food" } },
        { match = "radish",      path = { "Bartender", "Food" } },
        { match = "zucchini",    path = { "Bartender", "Food" } },
        { match = "sausage",     path = { "Bartender", "Food" } },
        { match = "bacon",       path = { "Bartender", "Food" } },
        { match = "steak",       path = { "Bartender", "Food" } },
        { match = "sardine",     path = { "Bartender", "Food" } },
        { match = "tuna",        path = { "Bartender", "Food" } },
        { match = "peach",       path = { "Bartender", "Food" } },
        { match = "plum",        path = { "Bartender", "Food" } },
        { match = "grape",       path = { "Bartender", "Food" } },
        { match = "melon",       path = { "Bartender", "Food" } },
        { match = "berry",       path = { "Bartender", "Food" } },
        { match = "pickle",      path = { "Bartender", "Food" } },
        { match = "honey",       path = { "Bartender", "Food" } },
        { match = "peanut",      path = { "Bartender", "Food" } },
        { match = "walnut",      path = { "Bartender", "Food" } },

        -- ===== GENERALGOODS (clothing & wearables) =====
        { match = "backpack",    path = { "GeneralGoods", "Backpacks" } },
        { match = "rucksack",    path = { "GeneralGoods", "Backpacks" } },
        { match = "helmet",      path = { "GeneralGoods", "Helmets" } },
        { match = "jacket",      path = { "GeneralGoods", "Jackets" } },
        { match = "coat",        path = { "GeneralGoods", "Jackets" } },
        { match = "hoodie",      path = { "GeneralGoods", "Jackets" } },
        { match = "jeans",       path = { "GeneralGoods", "Pants" } },
        { match = "pants",       path = { "GeneralGoods", "Pants" } },
        { match = "trousers",    path = { "GeneralGoods", "Pants" } },
        { match = "shorts",      path = { "GeneralGoods", "Pants" } },
        { match = "shirt",       path = { "GeneralGoods", "Tops" } },
        { match = "sweater",     path = { "GeneralGoods", "Tops" } },
        { match = "_top",        path = { "GeneralGoods", "Tops" } },
        { match = "boots",       path = { "GeneralGoods", "Feet" } },
        { match = "shoes",       path = { "GeneralGoods", "Feet" } },
        { match = "sneakers",    path = { "GeneralGoods", "Feet" } },
        { match = "_socks",      path = { "GeneralGoods", "Feet" } },
        { match = "gloves",      path = { "GeneralGoods", "Hands" } },
        { match = "mask",        path = { "GeneralGoods", "Face" } },
        { match = "glasses",     path = { "GeneralGoods", "Face" } },
        { match = "goggles",     path = { "GeneralGoods", "Face" } },
        { match = "_hat",        path = { "GeneralGoods", "Headwear" } },
        { match = "_cap",        path = { "GeneralGoods", "Headwear" } },
        { match = "beanie",      path = { "GeneralGoods", "Headwear" } },
        { match = "bandana",     path = { "GeneralGoods", "Headwear" } },
        { match = "vest",        path = { "GeneralGoods", "Armour" } },
        { match = "armor",       path = { "GeneralGoods", "Armour" } },
        { match = "armour",      path = { "GeneralGoods", "Armour" } },

        -- ===== HARBOURMASTER =====
        { match = "fishing",     path = { "Harbourmaster", "Fishing" } },
        { match = "_lure",       path = { "Harbourmaster", "Fishing" } },
        { match = "_bait",       path = { "Harbourmaster", "Fishing" } },
        { match = "boat",        path = { "Harbourmaster", "WaterVehicles" } },
        { match = "kayak",       path = { "Harbourmaster", "WaterVehicles" } },
        { match = "_paddle",     path = { "Harbourmaster", "WaterVehicles" } },

        -- ===== MECHANIC =====
        { match = "_wheel",      path = { "Mechanic", "Vehicles" } },
        { match = "_tire",       path = { "Mechanic", "Vehicles" } },
        { match = "jerry_can",   path = { "Mechanic", "Vehicles" } },
        { match = "nail",        path = { "Mechanic", "Crafting" } },
        { match = "plank",       path = { "Mechanic", "Crafting" } },
        { match = "rope",        path = { "Mechanic", "Crafting" } },
        { match = "duct_tape",   path = { "Mechanic", "Crafting" } },
        { match = "scrap",       path = { "Mechanic", "Crafting" } },
        { match = "_wire",       path = { "Mechanic", "Crafting" } },
        { match = "gunpowder",   path = { "Mechanic", "Crafting" } },
        { match = "_rag",        path = { "Mechanic", "Crafting" } },
        { match = "hammer",      path = { "Mechanic", "Crafting" } },
        { match = "wrench",      path = { "Mechanic", "Crafting" } },
        { match = "screwdriver", path = { "Mechanic", "Crafting" } },
        { match = "screw",       path = { "Mechanic", "Crafting" } },
        { match = "pliers",      path = { "Mechanic", "Crafting" } },
        { match = "drill",       path = { "Mechanic", "Crafting" } },
        { match = "glue",        path = { "Mechanic", "Crafting" } },
        { match = "_log",        path = { "Mechanic", "Crafting" } },
        { match = "charcoal",    path = { "Mechanic", "Crafting" } },
        { match = "cement",      path = { "Mechanic", "Crafting" } },
        { match = "plastic",     path = { "Mechanic", "Crafting" } },
        { match = "fertilizer",  path = { "Mechanic", "Crafting" } },

        -- ===== GAP-FILL RULES (derived from the SCUM wiki Item IDs list, 2026-05-28) =====
        -- Generated to cover items the hand-written tokens above missed; ~98% of 1341
        -- known item IDs now map. Edit/extend freely; 'goober classes' shows live gaps.
        { match = "brass_knuckles", path = { "Armorer", "MeleeWeapon" } },
        { match = "knuckles", path = { "Armorer", "MeleeWeapon" } },
        { match = "weaponsights", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "weaponflash", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "bowsight", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "flashhider", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "improvisedrail", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "_rail_", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "improvisedflashlight", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "hand_fan", path = { "Armorer", "RangedWeaponAccessories" } },
        { match = "flashbang", path = { "Armorer", "Explosives" } },
        { match = "pipebomb", path = { "Armorer", "Explosives" } },
        { match = "_bomb", path = { "Armorer", "Explosives" } },
        { match = "mine_0", path = { "Armorer", "Explosives" } },
        { match = "improvisedmine", path = { "Armorer", "Explosives" } },
        { match = "pressurecooker", path = { "Armorer", "Explosives" } },
        { match = "cal_30", path = { "Armorer", "Ammo" } },
        { match = "_clip", path = { "Armorer", "Ammo" } },
        { match = "ammobox", path = { "Armorer", "Ammo" } },
        { match = "flarecartridge", path = { "Armorer", "Ammo" } },
        { match = "12_gauge", path = { "Armorer", "Ammo" } },
        { match = "cal22", path = { "Armorer", "Ammo" } },
        { match = "cal30", path = { "Armorer", "Ammo" } },
        { match = "cal45", path = { "Armorer", "Ammo" } },
        { match = "cal7_", path = { "Armorer", "Ammo" } },
        { match = "cal_357", path = { "Armorer", "Ammo" } },
        { match = "cal_50", path = { "Armorer", "Ammo" } },
        { match = "cal_5_45", path = { "Armorer", "Ammo" } },
        { match = "cal_5_56", path = { "Armorer", "Ammo" } },
        { match = "cal_7_62", path = { "Armorer", "Ammo" } },
        { match = "cal_7_92", path = { "Armorer", "Ammo" } },
        { match = "cal_9mm", path = { "Armorer", "Ammo" } },
        { match = "cal_9x39", path = { "Armorer", "Ammo" } },
        { match = "cal_762", path = { "Armorer", "Ammo" } },
        { match = "cal_792", path = { "Armorer", "Ammo" } },
        { match = "brokenarrow", path = { "Armorer", "Ammo" } },
        { match = "_bullet", path = { "Armorer", "Ammo" } },
        { match = "_pile", path = { "Armorer", "Ammo" } },
        { match = "_5pcs", path = { "Armorer", "Ammo" } },
        { match = "_empty", path = { "Armorer", "Ammo" } },
        { match = "burger", path = { "Bartender", "Food" } },
        { match = "cake", path = { "Bartender", "Food" } },
        { match = "cantonese", path = { "Bartender", "Food" } },
        { match = "sweet_and_sour", path = { "Bartender", "Food" } },
        { match = "canningfood", path = { "Bartender", "Food" } },
        { match = "canopener", path = { "Mechanic", "Crafting" } },
        { match = "adrenaline", path = { "Doctor", "FirstAid" } },
        { match = "antimalaria", path = { "Doctor", "FirstAid" } },
        { match = "antiparasitic", path = { "Doctor", "FirstAid" } },
        { match = "aspirin", path = { "Doctor", "FirstAid" } },
        { match = "atropine", path = { "Doctor", "FirstAid" } },
        { match = "crutch", path = { "Doctor", "FirstAid" } },
        { match = "hemostatic", path = { "Doctor", "FirstAid" } },
        { match = "_dressing", path = { "Doctor", "FirstAid" } },
        { match = "penicillin", path = { "Doctor", "FirstAid" } },
        { match = "aseptic", path = { "Doctor", "FirstAid" } },
        { match = "pills", path = { "Doctor", "FirstAid" } },
        { match = "injection", path = { "Doctor", "FirstAid" } },
        { match = "fish_", path = { "Harbourmaster", "Fishing" } },
        { match = "boilie", path = { "Harbourmaster", "Fishing" } },
        { match = "absinthe", path = { "Bartender", "Alcohol" } },
        { match = "pelinkovac", path = { "Bartender", "Alcohol" } },
        { match = "tequila", path = { "Bartender", "Alcohol" } },
        { match = "reviver", path = { "Bartender", "Alcohol" } },
        { match = "slavic_gent", path = { "Bartender", "Alcohol" } },
        { match = "scum_sunrise", path = { "Bartender", "Alcohol" } },
        { match = "island_special", path = { "Bartender", "Alcohol" } },
        { match = "canteen", path = { "Bartender", "Drink" } },
        { match = "latte", path = { "Bartender", "Drink" } },
        { match = "glassbottle", path = { "Bartender", "Drink" } },
        { match = "petbottle", path = { "Bartender", "Drink" } },
        { match = "mushroom", path = { "Bartender", "Food" } },
        { match = "agaricus", path = { "Bartender", "Food" } },
        { match = "amanita", path = { "Bartender", "Food" } },
        { match = "amantia", path = { "Bartender", "Food" } },
        { match = "boletus", path = { "Bartender", "Food" } },
        { match = "cantharellus", path = { "Bartender", "Food" } },
        { match = "coprinus", path = { "Bartender", "Food" } },
        { match = "lepiota", path = { "Bartender", "Food" } },
        { match = "lycoperdon", path = { "Bartender", "Food" } },
        { match = "psilocybe", path = { "Bartender", "Food" } },
        { match = "beet", path = { "Bartender", "Food" } },
        { match = "broccoli", path = { "Bartender", "Food" } },
        { match = "cauliflower", path = { "Bartender", "Food" } },
        { match = "celery", path = { "Bartender", "Food" } },
        { match = "chilipeper", path = { "Bartender", "Food" } },
        { match = "coconut", path = { "Bartender", "Food" } },
        { match = "currant", path = { "Bartender", "Food" } },
        { match = "date", path = { "Bartender", "Food" } },
        { match = "_fig", path = { "Bartender", "Food" } },
        { match = "kiwi", path = { "Bartender", "Food" } },
        { match = "lemon", path = { "Bartender", "Food" } },
        { match = "lime", path = { "Bartender", "Food" } },
        { match = "mango", path = { "Bartender", "Food" } },
        { match = "orange", path = { "Bartender", "Food" } },
        { match = "parsley", path = { "Bartender", "Food" } },
        { match = "pear", path = { "Bartender", "Food" } },
        { match = "ramsons", path = { "Bartender", "Food" } },
        { match = "rice", path = { "Bartender", "Food" } },
        { match = "salsify", path = { "Bartender", "Food" } },
        { match = "blueberr", path = { "Bartender", "Food" } },
        { match = "dog_rose", path = { "Bartender", "Food" } },
        { match = "olive", path = { "Bartender", "Food" } },
        { match = "guava", path = { "Bartender", "Food" } },
        { match = "almond", path = { "Bartender", "Food" } },
        { match = "hazelnut", path = { "Bartender", "Food" } },
        { match = "oak_nuts", path = { "Bartender", "Food" } },
        { match = "pine_cone", path = { "Bartender", "Food" } },
        { match = "sunflower_seed", path = { "Bartender", "Food" } },
        { match = "crow_", path = { "Bartender", "Food" } },
        { match = "seagull", path = { "Bartender", "Food" } },
        { match = "larve", path = { "Bartender", "Food" } },
        { match = "animal_fat", path = { "Bartender", "Food" } },
        { match = "animal_guts", path = { "Bartender", "Food" } },
        { match = "ravioli", path = { "Bartender", "Food" } },
        { match = "spam", path = { "Bartender", "Food" } },
        { match = "babyfood", path = { "Bartender", "Food" } },
        { match = "butter", path = { "Bartender", "Food" } },
        { match = "cream", path = { "Bartender", "Food" } },
        { match = "chips", path = { "Bartender", "Food" } },
        { match = "crackers", path = { "Bartender", "Food" } },
        { match = "oatmeal", path = { "Bartender", "Food" } },
        { match = "mre", path = { "Bartender", "Food" } },
        { match = "fig", path = { "Bartender", "Food" } },
        { match = "isopropyl", path = { "Doctor", "FirstAid" } },
        { match = "armillaria", path = { "Bartender", "Food" } },
        { match = "bakevegetable", path = { "Bartender", "Food" } },
        { match = "aloe", path = { "Doctor", "FirstAid" } },
        { match = "_pils", path = { "Doctor", "FirstAid" } },
        { match = "_torso", path = { "Bartender", "Food" } },
        { match = "_back_leg", path = { "Bartender", "Food" } },
        { match = "_front_leg", path = { "Bartender", "Food" } },
        { match = "bird_brest", path = { "Bartender", "Food" } },
        { match = "bird_leg", path = { "Bartender", "Food" } },
        { match = "_skinned", path = { "Bartender", "Food" } },
        { match = "_antlers", path = { "Bartender", "Food" } },
        { match = "hooves", path = { "Bartender", "Food" } },
        { match = "bobby_pin", path = { "Mechanic", "Crafting" } },
        { match = "saftey_pin", path = { "Mechanic", "Crafting" } },
        { match = "_pins", path = { "Mechanic", "Crafting" } },
        { match = "anode", path = { "Mechanic", "Crafting" } },
        { match = "emptybag", path = { "GeneralGoods", "Backpacks" } },
        { match = "_limb", path = { "Bartender", "Food" } },
        { match = "chili_con", path = { "Bartender", "Food" } },
        { match = "chow_mein", path = { "Bartender", "Food" } },
        { match = "cooked_veg", path = { "Bartender", "Food" } },
        { match = "cookvegetable", path = { "Bartender", "Food" } },
        { match = "dandelion", path = { "Bartender", "Food" } },
        { match = "crab_", path = { "Bartender", "Food" } },
        { match = "_pincer", path = { "Bartender", "Food" } },
        { match = "cricket", path = { "Bartender", "Food" } },
        { match = "earthworm", path = { "Bartender", "Food" } },
        { match = "prisoner_left", path = { "Bartender", "Food" } },
        { match = "prisoner_right", path = { "Bartender", "Food" } },
        { match = "human_ears", path = { "Bartender", "Food" } },
        { match = "coal", path = { "Mechanic", "Crafting" } },
        { match = "feather", path = { "Mechanic", "Crafting" } },
        { match = "electrode", path = { "Mechanic", "Crafting" } },
        { match = "carbon", path = { "Mechanic", "Crafting" } },
        { match = "flint", path = { "Mechanic", "Crafting" } },
        { match = "lockpick", path = { "Mechanic", "Crafting" } },
        { match = "lock_item", path = { "Mechanic", "Crafting" } },
        { match = "human_skin", path = { "Mechanic", "Crafting" } },
        { match = "human_teeth", path = { "Mechanic", "Crafting" } },
        { match = "cigarette", path = { "GeneralGoods", "Misc" } },
        { match = "copper_coin", path = { "GeneralGoods", "Misc" } },
        { match = "diary", path = { "GeneralGoods", "Misc" } },
        { match = "arm_guard", path = { "GeneralGoods", "Armour" } },
        { match = "stew", path = { "Bartender", "Food" } },
        { match = "pasta", path = { "Bartender", "Food" } },
        { match = "toaster", path = { "Bartender", "Food" } },
        { match = "pepper", path = { "Bartender", "Food" } },
        { match = "seasalt", path = { "Bartender", "Food" } },
        { match = "soysauce", path = { "Bartender", "Food" } },
        { match = "spicesmix", path = { "Bartender", "Food" } },
        { match = "sugar", path = { "Bartender", "Food" } },
        { match = "vegetableoil", path = { "Bartender", "Food" } },
        { match = "vinegar", path = { "Bartender", "Food" } },
        { match = "whiteflour", path = { "Bartender", "Food" } },
        { match = "yeast", path = { "Bartender", "Food" } },
        { match = "_egg", path = { "Bartender", "Food" } },
        { match = "egg", path = { "Bartender", "Food" } },
        { match = "can0", path = { "Bartender", "Food" } },
        { match = "wild_cherry", path = { "Bartender", "Food" } },
        { match = "gasoline", path = { "Mechanic", "Vehicles" } },
        { match = "banjo", path = { "Mechanic", "Crafting" } },
        { match = "guitar", path = { "Mechanic", "Crafting" } },
        { match = "harmonica", path = { "Mechanic", "Crafting" } },
        { match = "_radio", path = { "Mechanic", "Crafting" } },
        { match = "compass", path = { "Mechanic", "Crafting" } },
        { match = "binocular", path = { "Mechanic", "Crafting" } },
        { match = "flare", path = { "Mechanic", "Crafting" } },
        { match = "candle", path = { "Mechanic", "Crafting" } },
        { match = "lighter", path = { "Mechanic", "Crafting" } },
        { match = "matches", path = { "Mechanic", "Crafting" } },
        { match = "sewing", path = { "Mechanic", "Crafting" } },
        { match = "tool_box", path = { "Mechanic", "Crafting" } },
        { match = "toolbox", path = { "Mechanic", "Crafting" } },
        { match = "repair_kit", path = { "Mechanic", "Crafting" } },
        { match = "grinding_stone", path = { "Mechanic", "Crafting" } },
        { match = "electrician", path = { "Mechanic", "Crafting" } },
        { match = "firecracker", path = { "Mechanic", "Crafting" } },
        { match = "electrical_repair", path = { "Mechanic", "Crafting" } },
        { match = "animal_skin", path = { "Mechanic", "Crafting" } },
        { match = "_head", path = { "Mechanic", "Crafting" } },
        { match = "_paws", path = { "Mechanic", "Crafting" } },
        { match = "bear_front", path = { "Mechanic", "Crafting" } },
        { match = "bone", path = { "Mechanic", "Crafting" } },
        { match = "stone", path = { "Mechanic", "Crafting" } },
        { match = "thread", path = { "Mechanic", "Crafting" } },
        { match = "paper", path = { "Mechanic", "Crafting" } },
        { match = "rag", path = { "Mechanic", "Crafting" } },
        { match = "rubber", path = { "Mechanic", "Crafting" } },
        { match = "bolts", path = { "Mechanic", "Crafting" } },
        { match = "batter", path = { "Mechanic", "Crafting" } },
        { match = "break_oil", path = { "Mechanic", "Crafting" } },
        { match = "camera_lens", path = { "Mechanic", "Crafting" } },
        { match = "lead_plate", path = { "Mechanic", "Crafting" } },
        { match = "gun_powder", path = { "Mechanic", "Crafting" } },
        { match = "tinder", path = { "Mechanic", "Crafting" } },
        { match = "_stick", path = { "Mechanic", "Crafting" } },
        { match = "_tips", path = { "Mechanic", "Crafting" } },
        { match = "christmas_tree", path = { "Mechanic", "Crafting" } },
        { match = "_wire", path = { "Mechanic", "Crafting" } },
        { match = "wire", path = { "Mechanic", "Crafting" } },
        { match = "necklace", path = { "GeneralGoods", "Cosmetics" } },
        { match = "beenie", path = { "GeneralGoods", "Headwear" } },
        { match = "headband", path = { "GeneralGoods", "Headwear" } },
        { match = "k6", path = { "GeneralGoods", "Helmets" } },
        { match = "respirator", path = { "GeneralGoods", "Face" } },
        { match = "breathing_tube", path = { "GeneralGoods", "Face" } },
        { match = "night_vision", path = { "GeneralGoods", "Face" } },
        { match = "googles", path = { "GeneralGoods", "Face" } },
        { match = "_shoe", path = { "GeneralGoods", "Feet" } },
        { match = "slipper", path = { "GeneralGoods", "Feet" } },
        { match = "socks", path = { "GeneralGoods", "Feet" } },
        { match = "tights", path = { "GeneralGoods", "Feet" } },
        { match = "bear_pow", path = { "GeneralGoods", "Feet" } },
        { match = "jersey", path = { "GeneralGoods", "Tops" } },
        { match = "spitfire", path = { "GeneralGoods", "Jackets" } },
        { match = "ma1_", path = { "GeneralGoods", "Jackets" } },
        { match = "bra", path = { "GeneralGoods", "Underwear" } },
        { match = "supporter", path = { "GeneralGoods", "Underwear" } },
        { match = "peniswarmer", path = { "GeneralGoods", "Underwear" } },
        { match = "mma_glove", path = { "GeneralGoods", "Hands" } },
        { match = "glove", path = { "GeneralGoods", "Hands" } },
        { match = "quiver", path = { "GeneralGoods", "Backpacks" } },
        { match = "_bag_", path = { "GeneralGoods", "Backpacks" } },
        { match = "sporran", path = { "GeneralGoods", "Backpacks" } },
        { match = "stabproof", path = { "GeneralGoods", "Armour" } },
        { match = "christmas", path = { "GeneralGoods", "Cosmetics" } },
    },

    -- Path for items no rule matched. Tries a "Misc" chest, then "GeneralGoods".
    -- Set to nil to leave unmatched items in place instead. Either way, unmatched
    -- classes are listed in the sweep log under "unmapped" so you know what still
    -- needs a rule.
    defaultPath = { "GeneralGoods", "Misc" },
}
